### ISSUE TITLE
NO NO NO NO MY LIFE IS OVER

### ISSUE THREAD

**Issue by Lux-14** [Chaannce/DesktopLocker#1]
WHY DID U DELETE TOOLS_P MAN WHY IT WAS SO AMAZING MAN PLEASE BRING IT BACK MAN PLEASE TOOLS_P IS SO AMAZING MAN WHYYYYYYYY

**Comment by NoSobriety** [comment]
NOO NOO CHANCE NO BRING BACK TOOLS_P I'M SO DEPRESSED NOW. TOOLS_P WAS THE KEY TO MY LIFE MAAAAANNNNN

**Comment by Lux-14** [comment]
MAN I WILL NEVER FORGET THE MEMORIES

**Comment by Lux-14** [comment]
R.I.P tools_p - 2022-2023
